### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by fernando24164**
Hi,

I wanted to tested it to try to help. I added a Dockerfile for running inside a container.
To build the container:
**docker build -t <name_you_want_for_the_container> .**
To run it:
**docker run -it <name_of_the_container>**

Thanks for sharing your code!

### CODE REVIEW

**Comment by UltimateHackers** [comment]
Sorry for being such a noob but I have no idea what a Dockerfile is.
What is it?
PS: I googled about it but that was a bit confusing for me.
Thanks for the contribution.

**Comment by fernando24164** [comment]
It is a container technology, in a nutshell is similar to virtualization but without hypervisor.
I added it because I want to create a test environment with a fake site and avoid launch it to an URL without control it.
I see the code hasn't multithreading in your readme and I think it would better if we can test it in a controlled environment to add that feature.

**Comment by UltimateHackers** [comment]
Ah I see but why would a normal user need that?

**Comment by fernando24164** [comment]
Well, in my opinion made application more portable. Docker is multiplatform and the virtual environments to avoid your global python get a lot of dependencies you don't really use it is a little headache. With this, you just can run it where you want and don't need to worry about anything.

**Pull request closed without merging**
