### PR TITLE
Enable MultiProcessing

### PR DESCRIPTION
**Pull request by V1n35h**
Multi-threading

### CODE REVIEW

**Comment by UltimateHackers** [comment]
I just checked your fork against **twitter.com/login** and it started throwing errors like crazy. Can you please test it again?
Thanks.

**Comment by V1n35h** [comment]
I Found To Many Bugs
1)twitter block our ip thats why title is change and programe print Valid credentials found
2)I set minimum sleep time to start new thread thats why urlerror 0 and BadStatusLine error
3) and we need to set error handling that cache error like forbidden,loop detect,urlerror etc
screenshot from 2017-10-05 10-37-53

Sorry For my English

**Comment by UltimateHackers** [comment]
Try your script on some other page then.
I have no experience of multi threading so its up to you.
Thanks for your support.

**Comment by V1n35h** [comment]
Now we can chose how many thread We want to run.
After Testing I will Commit

**Comment by V1n35h** [comment]
Sorry Bro

**Comment by UltimateHackers** [comment]
Sorry for what?

**Pull request closed without merging**
